name: SQL Workbench Test and Build

on: [pull_request, push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v1
      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.9.1
          path: sql/kibana
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.22.0'
      - name: Move Workbench to Plugins Dir
        run: |
          mkdir kibana/plugins
          mv workbench kibana/plugins
      - name: Kibana Plugin Bootstrap
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: cd kibana/plugins/workbench; yarn kbn bootstrap
      - name: Test
        run: |
          cd kibana/plugins/workbench
          yarn test:jest
      - name: Build Artifact
        run: |
          cd kibana/plugins/workbench
          yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: workbench
          path: kibana/plugins/workbench/build
